### ISSUE TITLE
Tenets + Requirements

### ISSUE THREAD

**Issue by haardikk21** [DecentralizedMessaging/messaging-spec#1]
Opening this thread to figure out overlaps in approach and goals

MailChain - https://github.com/mailchain/mailchain-specification/blob/master/mailchain_tenets.md

**Comment by haardikk21** [comment]
1. Security - Prioritize anonymity and secure messaging between actors on the network.

2. User Experience - UX should be intuitive, with a modern look-and-feel. 'Blockchain' experience should be minimized wherever possible.

3. Decentralized - Provide users the option to send and receive messages in a fully decentralized way - with no central chokepoints.

4. Scalability - Enable low cost and high frequency messaging across blockchains.

5. Interoperable Standards - Support and contribute towards building an **extensible** interoperable messaging standard for the community to adopt to lower barriers to entry.

**Comment by HarshRajat** [comment]
1. Security - Users need to be protected, their notifications (especially secrets) should be only accessible to them.

2. User Experience - Users should be expected to do minimal things in setup or otherwise, every thing should be automagical.

3. Decentralization - Every mapping, settings, notifications, etc should be stored (indirectly - ipfs, etc or directly) on decentralized solutions. ie: aim to be platform agnostic.

4. Flexibility - Notifications, Features should work exactly the same anywhere regardless of the platform user is on. ie: dApp, Mobile App, Web3 Providers, etc.

5. Low Cost / Protocol Optimization - The protocol should be optimized in every way possible to decrease the cost to the user without compromising on features.

**Comment by haardikk21** [comment]
Closing as this has been moved to agenda and discussed,
